
DROP TABLE SERVICE ;
DROP TABLE APPOINTMENT;
DROP TABLE  CLIENT;
DROP TABLE  WORKER;
DROP TABLE  PERSON;
DROP TABLE  HAIRSALON; 
DROP TABLE  LOCATION;  
DROP TABLE  CITY;  


CREATE TABLE CITY(
    cityID INT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    postNumber INT 
    
);    

CREATE TABLE LOCATION(
    locationID INT PRIMARY KEY,
    street VARCHAR(50) NOT NULL,
    FOREIGN KEY (cityID) REFERENCES CITY(cityID)
);
  

CREATE TABLE HAIRSALON(
    hairSalonID INT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    FOREIGN KEY (locationID) REFERENCES LOCATION(locationID)
);


CREATE TABLE PERSON(
    personID INT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    FOREIGN KEY (locationID) REFERENCES LOCATION(locationID)
);  

CREATE TABLE CLIENT (
    clientID INT PRIMARY KEY,
    membership BOOL NOT NULL
    CONSTRAINT FOREIGN KEY (clientID) REFERENCES PERSON(personID),
);

CREATE TABLE WORKER(
    workerID INT PRIMARY KEY,
    workHourse INT NOT NULL,
    salary FLOAT,
    CONSTRAINT FOREIGN KEY (workerID) REFERENCES PERSON(personID),
    FOREIGN KEY (hairSalonID) REFERENCES HAIRSALON(hairSalonID)
);


CREATE TABLE SERVICE (
    serviceID INT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    price NUMERIC(6,2)  NOT NULL
);

CREATE TABLE APPOINTMENT (
    appointmentID INT PRIMARY KEY,
    startTime TIMESTAMP NOT NULL,
    endTime   TIMESTAMP NOT NULL,
    FOREIGN KEY (clientID) REFERENCES CLIENT(clientID),
    FOREIGN KEY (workerID) REFERENCES WORKER(workerID),
    FOREIGN KEY (serviceID) REFERENCES SERVICE(serviceID)
   
);








